channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=25.1.1
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - pandas==2.0.3
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==3.0.0
name: mlflow-env
